// lazyload config

var jp_config = {
  easyPieChart:   [   'js/plugins/jquery.easy-pie-chart/dist/jquery.easypiechart.fill.js'],
  sparkline:      [   'js/plugins/jquery.sparkline/dist/jquery.sparkline.retina.js'],
  plot:           [   'js/plugins/flot/jquery.flot.js',
                      'js/plugins/flot/jquery.flot.pie.js', 
                      'js/plugins/flot/jquery.flot.resize.js',
                      'js/plugins/flot.tooltip/js/jquery.flot.tooltip.min.js',
                      'js/plugins/flot.orderbars/js/jquery.flot.orderBars.js',
                      'js/plugins/flot-spline/js/jquery.flot.spline.min.js'],
  moment:         [   'js/plugins/moment/moment.js'],
  screenfull:     [   'js/plugins/screenfull/dist/screenfull.min.js'],
  slimScroll:     [   'js/plugins/slimscroll/jquery.slimscroll.min.js'],
  sortable:       [   'js/plugins/html5sortable/jquery.sortable.js'],
  nestable:       [   'js/plugins/nestable/jquery.nestable.js',
                      'js/plugins/nestable/jquery.nestable.css'],
  filestyle:      [   'js/plugins/bootstrap-filestyle/src/bootstrap-filestyle.js'],
  slider:         [   'js/plugins/bootstrap-slider/bootstrap-slider.js',
                      'js/plugins/bootstrap-slider/bootstrap-slider.css'],
  chosen:         [   'js/plugins/chosen/chosen.jquery.min.js',
                      'js/plugins/chosen/bootstrap-chosen.css'],
  TouchSpin:      [   'js/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js',
                      'js/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css'],
  wysiwyg:        [   'js/plugins/bootstrap-wysiwyg/bootstrap-wysiwyg.js',
                      'js/plugins/bootstrap-wysiwyg/external/jquery.hotkeys.js'],
  dataTable:      [   'js/plugins/datatables/media/js/jquery.dataTables.min.js',
                      'js/plugins/plugins/integration/bootstrap/3/dataTables.bootstrap.js',
                      'js/plugins/plugins/integration/bootstrap/3/dataTables.bootstrap.css'],
  vectorMap:      [   'js/plugins/bower-jvectormap/jquery-jvectormap-1.2.2.min.js', 
                      'js/plugins/bower-jvectormap/jquery-jvectormap-world-mill-en.js',
                      'js/plugins/bower-jvectormap/jquery-jvectormap-us-aea-en.js',
                      'js/plugins/bower-jvectormap/jquery-jvectormap.css'],
  footable:       [   'js/plugins/footable/dist/footable.all.min.js',
                      'js/plugins/footable/css/footable.core.css'],
  fullcalendar:   [   'js/plugins/moment/moment.js',
                      'js/plugins/fullcalendar/dist/fullcalendar.min.js',
                      'js/plugins/fullcalendar/dist/fullcalendar.css',
                      'js/plugins/fullcalendar/dist/fullcalendar.theme.css'],
  daterangepicker:[   'js/plugins/moment/moment.js',
                      'js/plugins/bootstrap-daterangepicker/daterangepicker.js',
                      'js/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css'],
  tagsinput:      [   'js/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.js',
                      'js/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css']
                      
};
